#!/usr/bin/env python3
"""Dynamic Assistant Tooling Installer.

Generates and registers assistant-specific hooks, skills, and memory files
(Git pre-commit hook, Antigravity skills/hooks, Claude Code commands/memory)
from canonical rules without manual repository clutter.
"""

from __future__ import annotations

import argparse
import os
import stat
from pathlib import Path

GIT_HOOK_TEMPLATE = """#!/bin/sh
# Auto-generated by scripts/install_tooling.py. Do not edit manually.
python3 scripts/pre_commit_reviewer.py
"""

ANTIGRAVITY_SKILL_TEMPLATE = """---
name: code-auditor
description: Audits staged or working-tree code diffs against repository canonical best-practice rules in .agents/rules/.
---

# Code Auditor Skill

This skill allows the agent to evaluate current git changes against the repository's canonical best-practice rules located in `.agents/rules/`.

## Instructions
1. Run `python3 scripts/pre_commit_reviewer.py` to evaluate staged changes.
2. If violations are reported, inspect each reported file and line number.
3. Automatically correct any `CRITICAL` or `ERROR` violations, stage the files with `git add`, and re-test.
4. Address `WARN` advisories if applicable to current task scope.
"""

ANTIGRAVITY_HOOKS_TEMPLATE = """{
  "description": "Auto-generated Antigravity hooks configuration",
  "hooks": {
    "PreCommit": {
      "command": "python3 scripts/pre_commit_reviewer.py",
      "blocking": true
    }
  }
}
"""

CLAUDE_COMMAND_TEMPLATE = """# On-Demand Code Best-Practices Audit

Execute the repository's universal code review engine to audit staged changes:

```bash
python3 scripts/pre_commit_reviewer.py
```

Review the diagnostic output and remediate any reported violations.
"""

CLAUDE_MEMORY_POINTER_BLOCK = """
<!-- BEGIN CANONICAL RULES POINTER (Auto-generated by scripts/install_tooling.py) -->
## Repository Standards & Canonical Rules
- Canonical best-practice rules and guidelines are maintained in `.agents/rules/`.
- Review staged diffs with `python3 scripts/pre_commit_reviewer.py` before committing.
<!-- END CANONICAL RULES POINTER -->
"""


def install_git_hook(root_dir: Path) -> bool:
    """Install git pre-commit hook."""
    git_hooks_dir = root_dir / ".git" / "hooks"
    if not git_hooks_dir.exists():
        print(f"Skipping Git hook: {git_hooks_dir} not found (not a git root).")
        return False

    hook_file = git_hooks_dir / "pre-commit"
    hook_file.write_text(GIT_HOOK_TEMPLATE, encoding="utf-8")
    # Make executable (chmod +x)
    current_mode = hook_file.stat().st_mode
    hook_file.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"✅ Installed Git pre-commit hook -> {hook_file}")
    return True


def install_antigravity(root_dir: Path) -> bool:
    """Install Antigravity skill and hooks configuration."""
    skill_dir = root_dir / ".agents" / "skills" / "code-auditor"
    skill_dir.mkdir(parents=True, exist_ok=True)
    skill_file = skill_dir / "SKILL.md"
    skill_file.write_text(ANTIGRAVITY_SKILL_TEMPLATE, encoding="utf-8")

    hooks_file = root_dir / ".agents" / "hooks.json"
    hooks_file.write_text(ANTIGRAVITY_HOOKS_TEMPLATE, encoding="utf-8")

    print(f"✅ Installed Antigravity skill -> {skill_file}")
    print(f"✅ Installed Antigravity hooks -> {hooks_file}")
    return True


def install_claude(root_dir: Path) -> bool:
    """Install Claude Code commands and memory pointer."""
    commands_dir = root_dir / ".claude" / "commands"
    commands_dir.mkdir(parents=True, exist_ok=True)
    command_file = commands_dir / "audit.md"
    command_file.write_text(CLAUDE_COMMAND_TEMPLATE, encoding="utf-8")

    claude_md = root_dir / "CLAUDE.md"
    content = claude_md.read_text(encoding="utf-8") if claude_md.exists() else "# Claude Memory\n"
    if "BEGIN CANONICAL RULES POINTER" not in content:
        content = content.rstrip() + "\n" + CLAUDE_MEMORY_POINTER_BLOCK
        claude_md.write_text(content, encoding="utf-8")

    print(f"✅ Installed Claude Code command -> {command_file}")
    print(f"✅ Updated Claude Memory pointer -> {claude_md}")
    return True


def clean_tooling(root_dir: Path) -> None:
    """Remove generated assistant artifacts."""
    git_hook = root_dir / ".git" / "hooks" / "pre-commit"
    if git_hook.exists():
        git_hook.unlink()
        print(f"🗑️  Removed {git_hook}")

    ag_skill = root_dir / ".agents" / "skills" / "code-auditor" / "SKILL.md"
    if ag_skill.exists():
        ag_skill.unlink()
        print(f"🗑️  Removed {ag_skill}")

    ag_hooks = root_dir / ".agents" / "hooks.json"
    if ag_hooks.exists():
        ag_hooks.unlink()
        print(f"🗑️  Removed {ag_hooks}")

    claude_cmd = root_dir / ".claude" / "commands" / "audit.md"
    if claude_cmd.exists():
        claude_cmd.unlink()
        print(f"🗑️  Removed {claude_cmd}")

    claude_md = root_dir / "CLAUDE.md"
    if claude_md.exists():
        content = claude_md.read_text(encoding="utf-8")
        if "BEGIN CANONICAL RULES POINTER" in content:
            # Strip block
            start_tag = "<!-- BEGIN CANONICAL RULES POINTER"
            end_tag = "<!-- END CANONICAL RULES POINTER -->"
            start_idx = content.find(start_tag)
            end_idx = content.find(end_tag)
            if start_idx != -1 and end_idx != -1:
                cleaned = content[:start_idx] + content[end_idx + len(end_tag) :]
                cleaned = cleaned.strip() + "\n"
                if cleaned.strip() in ("", "# Claude Memory"):
                    claude_md.unlink()
                    print(f"🗑️  Removed {claude_md}")
                else:
                    claude_md.write_text(cleaned, encoding="utf-8")
                    print(f"🗑️  Cleaned pointer in {claude_md}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Dynamic Assistant Tooling Installer")
    parser.add_argument("--all", action="store_true", help="Install all tooling & hooks")
    parser.add_argument("--git-hook", action="store_true", help="Install Git pre-commit hook")
    parser.add_argument("--antigravity", action="store_true", help="Install Antigravity skills & hooks")
    parser.add_argument("--claude", action="store_true", help="Install Claude Code commands & memory")
    parser.add_argument("--clean", action="store_true", help="Remove all generated assistant artifacts")
    parser.add_argument("--root-dir", default=".", help="Root repository path (default: .)")

    args = parser.parse_args()
    root_dir = Path(args.root_dir).resolve()

    if args.clean:
        clean_tooling(root_dir)
        return

    if args.all or (not args.git_hook and not args.antigravity and not args.claude):
        install_git_hook(root_dir)
        install_antigravity(root_dir)
        install_claude(root_dir)
        return

    if args.git_hook:
        install_git_hook(root_dir)
    if args.antigravity:
        install_antigravity(root_dir)
    if args.claude:
        install_claude(root_dir)


if __name__ == "__main__":
    main()
