#!/usr/bin/env python3
"""Dynamic Assistant Tooling Installer.

Generates and registers assistant-specific hooks, skills, and memory files
(Git pre-commit hook, Antigravity skills/hooks, Claude Code commands/memory, AGENTS.md pointer)
from canonical rules without manual repository clutter.
"""

from __future__ import annotations

import argparse
import os
import shutil
import stat
import sys
from pathlib import Path

GIT_HOOK_TEMPLATE = """#!/bin/sh
# Auto-generated by scripts/install_tooling.py. Do not edit manually.
python3 scripts/pre_commit_reviewer.py
"""

ANTIGRAVITY_AUDIT_SKILL_TEMPLATE = """---
name: code-auditor
description: Audits staged or working-tree code diffs against repository canonical best-practice rules in .agents/rules/.
---

# Code Auditor Skill

This skill allows the agent to evaluate current git changes against the repository's canonical best-practice rules located in `.agents/rules/`.

## Instructions
1. Run `python3 scripts/pre_commit_reviewer.py` to evaluate staged changes.
2. If violations are reported, inspect each reported file and line number.
3. Automatically correct any `CRITICAL` or `ERROR` violations, stage the files with `git add`, and re-test.
4. Address `WARN` advisories if applicable to current task scope.
"""

ANTIGRAVITY_PREFERENCES_SKILL_TEMPLATE = """---
name: personal-preferences
description: Captures, updates, and persists developer workflow preferences, habits, and engineering conventions into .agents/rules/05_personal_preferences.md. Detects generally applicable workflow comments and always requests explicit user confirmation before recording new rules.
---

# Personal Preferences & Workflow Rules Skill

This skill enables the coding assistant to capture user engineering preferences, workflow conventions, and pair-programming guidelines, and persist them to `.agents/rules/05_personal_preferences.md`.

## Triggers & Usage

Activate this skill when:
1. **Explicit User Intent**: The user asks to remember, add, update, list, or remove a coding or workflow preference / rule.
2. **Implicit Workflow Comments**: The assistant detects the user providing workflow-level feedback, corrections, or behavioral preferences that have general applicability across future tasks (e.g., preference for specific library patterns, formatting choices, confirmation checkpoints, error handling styles).

## Operational Workflow

### 1. General Workflow Feedback Detection
When the user gives feedback or instructions that are not merely one-off code edits but represent broader engineering preferences:
- Analyze whether the feedback applies generally to future coding or workflow interactions.
- Formulate a clear, concise, actionable rule statement.

### 2. Mandatory User Confirmation (STRICT REQUIREMENT)
> [!IMPORTANT]
> **NEVER silently add or modify rules in `.agents/rules/05_personal_preferences.md`.**
> You MUST ALWAYS explicitly ask the user for confirmation before recording or modifying any preference.

Example confirmation prompt:
> "I noticed you mentioned [specific preference or workflow comment]. Would you like me to record this as a rule in `.agents/rules/05_personal_preferences.md` so that future sessions automatically adhere to it?"

### 3. Recording Preferences
Once explicit confirmation is received from the user:
- Run the preference manager CLI:
  ```bash
  python3 scripts/preference_manager.py --add "<Rule description>" --section "<1. General Workflow Preferences | 2. Code Style & Engineering Conventions | 3. Tooling & Environment Preferences>"
  ```
- Or inspect existing preferences:
  ```bash
  python3 scripts/preference_manager.py --list
  ```
- Confirm to the user that the preference has been recorded and is now part of the active canonical rules reviewed during development and pre-commit checks.
"""

ANTIGRAVITY_HOOKS_TEMPLATE = """{
  "description": "Auto-generated Antigravity hooks configuration",
  "hooks": {
    "PreCommit": {
      "command": "python3 scripts/pre_commit_reviewer.py",
      "blocking": true
    }
  }
}
"""

CLAUDE_AUDIT_COMMAND_TEMPLATE = """# On-Demand Code Best-Practices Audit

Execute the repository's universal code review engine to audit staged changes:

```bash
python3 scripts/pre_commit_reviewer.py
```

Review the diagnostic output and remediate any reported violations.
"""

CLAUDE_PREFERENCES_COMMAND_TEMPLATE = """# Personal Engineering Preferences Manager

Manage custom workflow rules and preferences stored in `.agents/rules/05_personal_preferences.md`:

```bash
# List all recorded preferences
python3 scripts/preference_manager.py --list

# Add a preference under a specific section
python3 scripts/preference_manager.py --add "Always use explicit type annotations" --section "2. Code Style & Engineering Conventions"
```

Always obtain explicit confirmation from the user before recording new preferences.
"""

POINTER_START_TAG = "<!-- BEGIN CANONICAL RULES POINTER (Auto-generated by scripts/install_tooling.py) -->"
POINTER_END_TAG = "<!-- END CANONICAL RULES POINTER -->"

AGENTS_MEMORY_POINTER_BLOCK = """<!-- BEGIN CANONICAL RULES POINTER (Auto-generated by scripts/install_tooling.py) -->
## Repository Standards & Canonical Rules
- Canonical best-practice rules and guidelines are maintained in `.agents/rules/`.
- Custom developer and workflow preferences are managed in `.agents/rules/05_personal_preferences.md`.
<!-- END CANONICAL RULES POINTER -->"""

CLAUDE_MEMORY_POINTER_BLOCK = """<!-- BEGIN CANONICAL RULES POINTER (Auto-generated by scripts/install_tooling.py) -->
## Repository Standards & Canonical Rules
- Canonical best-practice rules and guidelines are maintained in `.agents/rules/`.
- Custom developer and workflow preferences are managed in `.agents/rules/05_personal_preferences.md`.
- Collaboration guidelines and branch policies are maintained in `AGENTS.md`.
<!-- END CANONICAL RULES POINTER -->"""

DEFAULT_AGENTS_TEMPLATE = """# Human-Agent Collaboration Protocol & Repository Guidelines

<!-- BEGIN CANONICAL RULES POINTER (Auto-generated by scripts/install_tooling.py) -->
## Repository Standards & Canonical Rules
- Canonical best-practice rules and guidelines are maintained in `.agents/rules/`.
- Custom developer and workflow preferences are managed in `.agents/rules/05_personal_preferences.md`.
<!-- END CANONICAL RULES POINTER -->
"""


def find_existing_file(root_dir: Path, candidates: tuple[str, ...]) -> Path | None:
    """Find the first matching candidate file in root_dir (case-insensitive check)."""
    for name in candidates:
        candidate_path = root_dir / name
        if candidate_path.is_file():
            return candidate_path

    candidates_lower = {c.lower(): c for c in candidates}
    try:
        for entry in root_dir.iterdir():
            if entry.is_file() and entry.name.lower() in candidates_lower:
                return entry
    except OSError:
        pass
    return None


def ask_permission(file_path: Path, assume_yes: bool = False) -> bool:
    """Prompt the user for permission to inject canonical rules pointer.

    Notifies the user that this is an insert-only operation.
    """
    if assume_yes:
        return True

    print(f"\n📄 Found existing non-empty file: {file_path.name}")
    print("ℹ️  Note: This is an insert-only operation that appends the canonical rules pointer without modifying or overwriting your existing content.")

    if not sys.stdin.isatty():
        print(f"⚠️  Non-interactive terminal detected. Skipping pointer injection into {file_path.name}. (Use -y/--yes to accept)")
        return False

    try:
        response = input(f"Do you grant permission to add the rules pointer to {file_path.name}? [y/N]: ").strip().lower()
        return response in ("y", "yes")
    except (EOFError, KeyboardInterrupt):
        print("\nOperation cancelled by user.")
        return False


def strip_pointer_block(content: str) -> str:
    """Remove the auto-generated pointer block if present."""
    start_idx = content.find("<!-- BEGIN CANONICAL RULES POINTER")
    end_tag = "<!-- END CANONICAL RULES POINTER -->"
    end_idx = content.find(end_tag)
    if start_idx != -1 and end_idx != -1:
        cleaned = content[:start_idx] + content[end_idx + len(end_tag) :]
        return cleaned.strip() + "\n"
    return content


def install_git_hook(root_dir: Path) -> bool:
    """Install git pre-commit hook."""
    git_hooks_dir = root_dir / ".git" / "hooks"
    if not git_hooks_dir.exists():
        print(f"Skipping Git hook: {git_hooks_dir} not found (not a git root).")
        return False

    hook_file = git_hooks_dir / "pre-commit"
    hook_file.write_text(GIT_HOOK_TEMPLATE, encoding="utf-8")
    current_mode = hook_file.stat().st_mode
    hook_file.chmod(current_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    print(f"✅ Installed Git pre-commit hook -> {hook_file}")
    return True


def install_antigravity(root_dir: Path) -> bool:
    """Install Antigravity skills and hooks configuration."""
    audit_skill_dir = root_dir / ".agents" / "skills" / "code-auditor"
    audit_skill_dir.mkdir(parents=True, exist_ok=True)
    audit_skill_file = audit_skill_dir / "SKILL.md"
    audit_skill_file.write_text(ANTIGRAVITY_AUDIT_SKILL_TEMPLATE, encoding="utf-8")

    pref_skill_dir = root_dir / ".agents" / "skills" / "personal-preferences"
    pref_skill_dir.mkdir(parents=True, exist_ok=True)
    pref_skill_file = pref_skill_dir / "SKILL.md"
    pref_skill_file.write_text(ANTIGRAVITY_PREFERENCES_SKILL_TEMPLATE, encoding="utf-8")

    hooks_file = root_dir / ".agents" / "hooks.json"
    hooks_file.write_text(ANTIGRAVITY_HOOKS_TEMPLATE, encoding="utf-8")

    print(f"✅ Installed Antigravity skill -> {audit_skill_file}")
    print(f"✅ Installed Antigravity skill -> {pref_skill_file}")
    print(f"✅ Installed Antigravity hooks -> {hooks_file}")
    return True


def ensure_agents_file(root_dir: Path, assume_yes: bool = False) -> bool:
    """Ensure AGENTS.md (or agents.md) exists and contains canonical rules pointer."""
    agents_file = find_existing_file(root_dir, ("AGENTS.md", "agents.md"))
    if agents_file and agents_file.is_file():
        content = agents_file.read_text(encoding="utf-8")
        if "BEGIN CANONICAL RULES POINTER" in content:
            print(f"ℹ️  Canonical rules pointer already present in {agents_file.name}")
            return True
        if content.strip():
            if not ask_permission(agents_file, assume_yes=assume_yes):
                print(f"⏭️  Skipped adding pointer to {agents_file.name} (permission denied).")
                return False
            new_content = content.rstrip() + "\n\n" + AGENTS_MEMORY_POINTER_BLOCK + "\n"
            agents_file.write_text(new_content, encoding="utf-8")
            print(f"✅ Inserted canonical rules pointer into {agents_file.name}")
            return True
        else:
            agents_file.write_text(DEFAULT_AGENTS_TEMPLATE.strip() + "\n", encoding="utf-8")
            print(f"✅ Initialized empty {agents_file.name} with canonical rules pointer")
            return True
    else:
        agents_file = root_dir / "AGENTS.md"
        agents_file.write_text(DEFAULT_AGENTS_TEMPLATE.strip() + "\n", encoding="utf-8")
        print(f"✅ Created {agents_file.name} with canonical rules pointer")
        return True


def install_claude(root_dir: Path, assume_yes: bool = False) -> bool:
    """Install Claude Code commands and update existing CLAUDE.md if present."""
    commands_dir = root_dir / ".claude" / "commands"
    commands_dir.mkdir(parents=True, exist_ok=True)

    audit_command_file = commands_dir / "audit.md"
    audit_command_file.write_text(CLAUDE_AUDIT_COMMAND_TEMPLATE, encoding="utf-8")

    pref_command_file = commands_dir / "preferences.md"
    pref_command_file.write_text(CLAUDE_PREFERENCES_COMMAND_TEMPLATE, encoding="utf-8")

    print(f"✅ Installed Claude Code command -> {audit_command_file}")
    print(f"✅ Installed Claude Code command -> {pref_command_file}")

    claude_file = find_existing_file(root_dir, ("CLAUDE.md", "claude.md"))
    if claude_file and claude_file.is_file():
        content = claude_file.read_text(encoding="utf-8")
        if "BEGIN CANONICAL RULES POINTER" in content:
            print(f"ℹ️  Canonical rules pointer already present in {claude_file.name}")
        elif content.strip():
            if not ask_permission(claude_file, assume_yes=assume_yes):
                print(f"⏭️  Skipped adding pointer to {claude_file.name} (permission denied).")
            else:
                new_content = content.rstrip() + "\n\n" + CLAUDE_MEMORY_POINTER_BLOCK + "\n"
                claude_file.write_text(new_content, encoding="utf-8")
                print(f"✅ Inserted canonical rules pointer into {claude_file.name}")
        else:
            claude_file.write_text("# Claude Memory\n\n" + CLAUDE_MEMORY_POINTER_BLOCK + "\n", encoding="utf-8")
            print(f"✅ Initialized empty {claude_file.name} with canonical rules pointer")
    else:
        print("ℹ️  No CLAUDE.md found. Claude Code will automatically fall back to AGENTS.md (no CLAUDE.md created).")

    return True


def clean_tooling(root_dir: Path) -> None:
    """Remove generated assistant artifacts and pointers."""
    git_hook = root_dir / ".git" / "hooks" / "pre-commit"
    if git_hook.exists():
        git_hook.unlink()
        print(f"🗑️  Removed {git_hook}")

    ag_audit_skill = root_dir / ".agents" / "skills" / "code-auditor" / "SKILL.md"
    if ag_audit_skill.exists():
        ag_audit_skill.unlink()
        print(f"🗑️  Removed {ag_audit_skill}")
    ag_audit_dir = root_dir / ".agents" / "skills" / "code-auditor"
    if ag_audit_dir.exists() and not any(ag_audit_dir.iterdir()):
        ag_audit_dir.rmdir()

    ag_pref_skill = root_dir / ".agents" / "skills" / "personal-preferences" / "SKILL.md"
    if ag_pref_skill.exists():
        ag_pref_skill.unlink()
        print(f"🗑️  Removed {ag_pref_skill}")
    ag_pref_dir = root_dir / ".agents" / "skills" / "personal-preferences"
    if ag_pref_dir.exists() and not any(ag_pref_dir.iterdir()):
        ag_pref_dir.rmdir()

    ag_hooks = root_dir / ".agents" / "hooks.json"
    if ag_hooks.exists():
        ag_hooks.unlink()
        print(f"🗑️  Removed {ag_hooks}")

    claude_audit_cmd = root_dir / ".claude" / "commands" / "audit.md"
    if claude_audit_cmd.exists():
        claude_audit_cmd.unlink()
        print(f"🗑️  Removed {claude_audit_cmd}")

    claude_pref_cmd = root_dir / ".claude" / "commands" / "preferences.md"
    if claude_pref_cmd.exists():
        claude_pref_cmd.unlink()
        print(f"🗑️  Removed {claude_pref_cmd}")

    claude_cmd_dir = root_dir / ".claude" / "commands"
    if claude_cmd_dir.exists() and not any(claude_cmd_dir.iterdir()):
        claude_cmd_dir.rmdir()
    claude_dir = root_dir / ".claude"
    if claude_dir.exists() and not any(claude_dir.iterdir()):
        claude_dir.rmdir()

    # Clean CLAUDE.md / claude.md
    claude_file = find_existing_file(root_dir, ("CLAUDE.md", "claude.md"))
    if claude_file and claude_file.exists():
        content = claude_file.read_text(encoding="utf-8")
        if "BEGIN CANONICAL RULES POINTER" in content:
            cleaned = strip_pointer_block(content)
            if cleaned.strip() in ("", "# Claude Memory"):
                claude_file.unlink()
                print(f"🗑️  Removed {claude_file.name}")
            else:
                claude_file.write_text(cleaned, encoding="utf-8")
                print(f"🗑️  Cleaned pointer in {claude_file.name} (preserved user memory)")

    # Clean AGENTS.md / agents.md
    agents_file = find_existing_file(root_dir, ("AGENTS.md", "agents.md"))
    if agents_file and agents_file.exists():
        content = agents_file.read_text(encoding="utf-8")
        if "BEGIN CANONICAL RULES POINTER" in content:
            cleaned = strip_pointer_block(content)
            if cleaned.strip() in (
                "",
                "# Human-Agent Collaboration Protocol & Repository Guidelines",
                "# Agent Collaboration Guidelines",
                "# Agents",
            ):
                agents_file.unlink()
                print(f"🗑️  Removed empty template {agents_file.name}")
            else:
                agents_file.write_text(cleaned, encoding="utf-8")
                print(f"🗑️  Cleaned pointer in {agents_file.name} (preserved user guidelines)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Dynamic Assistant Tooling Installer")
    parser.add_argument("--all", action="store_true", help="Install all tooling, hooks, and guidelines")
    parser.add_argument("--git-hook", action="store_true", help="Install Git pre-commit hook")
    parser.add_argument("--antigravity", action="store_true", help="Install Antigravity skills & hooks")
    parser.add_argument("--claude", action="store_true", help="Install Claude Code commands & memory pointer")
    parser.add_argument("--agents", action="store_true", help="Ensure AGENTS.md canonical rules pointer")
    parser.add_argument("--clean", action="store_true", help="Remove all generated assistant artifacts")
    parser.add_argument("-y", "--yes", action="store_true", help="Automatically accept insert-only pointer injection prompts")
    parser.add_argument("--root-dir", default=".", help="Root repository path (default: .)")

    args = parser.parse_args()
    root_dir = Path(args.root_dir).resolve()

    if args.clean:
        clean_tooling(root_dir)
        return

    specific_requested = args.git_hook or args.antigravity or args.claude or args.agents

    if args.all or not specific_requested:
        install_git_hook(root_dir)
        install_antigravity(root_dir)
        ensure_agents_file(root_dir, assume_yes=args.yes)
        install_claude(root_dir, assume_yes=args.yes)
        return

    if args.git_hook:
        install_git_hook(root_dir)
    if args.antigravity:
        install_antigravity(root_dir)
    if args.agents:
        ensure_agents_file(root_dir, assume_yes=args.yes)
    if args.claude:
        install_claude(root_dir, assume_yes=args.yes)


if __name__ == "__main__":
    main()
